const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function show(id){ $$('.view').forEach(v=>v.classList.toggle('active',v.id===id)); $$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id)); if(id==='snake') drawSnake(); if(id==='tower') drawTower(); window.scrollTo(0,0); }
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view))); $('.brand').addEventListener('click',()=>show('home')); $('.nav-link[data-view="home"]').addEventListener('click',()=>show('home'));
$$('.back').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view||'home')));

// Snake
const sc=$('#snake-canvas'), sx=sc.getContext('2d'); let snake=[], apple={}, dir={x:1,y:0}, nextDir=dir, snakeTimer, snakeScore=0, snakeRun=false;
function newSnake(){const n=+$('#snake-size').value; snake=[{x:Math.floor(n/2),y:Math.floor(n/2)},{x:Math.floor(n/2)-1,y:Math.floor(n/2)}];dir={x:1,y:0};nextDir=dir;snakeScore=0; $('#snake-score').textContent=0; appleSpot();drawSnake()}
function appleSpot(){const n=+$('#snake-size').value; do apple={x:Math.floor(Math.random()*n),y:Math.floor(Math.random()*n)};while(snake.some(p=>p.x===apple.x&&p.y===apple.y))}
function drawSnake(){const n=+$('#snake-size').value, z=sc.width/n; sx.fillStyle='#a8de94';sx.fillRect(0,0,600,600);sx.strokeStyle='#92cd86';sx.lineWidth=1;for(let i=0;i<=n;i++){sx.beginPath();sx.moveTo(i*z,0);sx.lineTo(i*z,600);sx.moveTo(0,i*z);sx.lineTo(600,i*z);sx.stroke()}sx.fillStyle='#f45d52';sx.beginPath();sx.arc((apple.x+.5)*z,(apple.y+.55)*z,z*.31,0,7);sx.fill();sx.fillStyle='#4d9255';sx.fillRect((apple.x+.54)*z,(apple.y+.16)*z,z*.11,z*.19); snake.forEach((p,i)=>{sx.fillStyle=i?'#417c4d':'#315f3a';sx.beginPath();sx.roundRect(p.x*z+2,p.y*z+2,z-4,z-4,Math.max(4,z*.18));sx.fill();if(!i){sx.fillStyle='white';sx.fillRect(p.x*z+z*.66,p.y*z+z*.24,z*.12,z*.12)}})}
function snakeStep(){dir=nextDir;const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y},n=+$('#snake-size').value;if(h.x<0||h.y<0||h.x>=n||h.y>=n||snake.some(p=>p.x===h.x&&p.y===h.y))return endSnake();snake.unshift(h);if(h.x===apple.x&&h.y===apple.y){snakeScore+=10;$('#snake-score').textContent=snakeScore;appleSpot()}else snake.pop();drawSnake()}
function endSnake(){clearInterval(snakeTimer);snakeRun=false;$('#snake-overlay').innerHTML='<h2>Snack run over!</h2><p>You collected '+snakeScore+' points.</p><button class="primary" id="snake-start">Try again <span>↻</span></button>';$('#snake-overlay').style.display='flex';$('#snake-start').onclick=startSnake}
function startSnake(){newSnake();snakeRun=true;$('#snake-overlay').style.display='none';clearInterval(snakeTimer);snakeTimer=setInterval(snakeStep,+$('#snake-speed').value)}
$('#snake-start').onclick=startSnake; $('#snake-size').addEventListener('change',newSnake);document.addEventListener('keydown',e=>{if(!snakeRun)return;const map={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const d=map[e.key];if(d&&!(d[0]===-dir.x&&d[1]===-dir.y)){e.preventDefault();nextDir={x:d[0],y:d[1]}}});newSnake();

// Blocks
$('#blocks-start').onclick=()=>$('#blocks-overlay').style.display='none';
const shapes=[[[0,0],[1,0],[0,1],[1,1]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[1,1]],[[0,0],[1,0],[2,0],[1,1]],[[0,0]],[[0,0],[1,0],[2,0],[3,0]]], colors=['#f57c55','#8067d5','#5bc4af','#efa94b'];let board, pieces, chosen=null, blockScore=0;
function newBlocks(){board=Array.from({length:10},()=>Array(10).fill(null));blockScore=0;$('#block-score').textContent=0; pieces=Array.from({length:3},()=>({shape:shapes[Math.floor(Math.random()*shapes.length)],color:colors[Math.floor(Math.random()*colors.length)]}));renderBlocks()}
function renderBlocks(){const bb=$('#block-board');bb.innerHTML='';board.flatMap((r,y)=>r.map((v,x)=>({v,x,y}))).forEach(c=>{let el=document.createElement('button');el.className='cell'+(c.v?' filled':'');if(c.v)el.style.setProperty('--cell-color',c.v);el.onclick=()=>place(c.x,c.y);bb.append(el)});const ps=$('#pieces');ps.innerHTML='';pieces.forEach((p,i)=>{if(!p)return;let e=document.createElement('button');e.className='piece'+(chosen===i?' selected':'');let mx=Math.max(...p.shape.map(x=>x[0]))+1,my=Math.max(...p.shape.map(x=>x[1]))+1;let g=document.createElement('div');g.className='piece-grid';g.style.gridTemplateColumns=`repeat(${mx},17px)`;g.style.gridTemplateRows=`repeat(${my},17px)`;p.shape.forEach(([x,y])=>{let c=document.createElement('i');c.className='piece-cell';c.style.cssText=`--piece-color:${p.color};grid-column:${x+1};grid-row:${y+1}`;g.append(c)});e.append(g);e.onclick=()=>{chosen=i;renderBlocks()};ps.append(e)})}
function place(x,y){let p=pieces[chosen];if(!p)return;if(p.shape.some(([a,b])=>x+a>9||y+b>9||board[y+b][x+a]))return; p.shape.forEach(([a,b])=>board[y+b][x+a]=p.color);pieces[chosen]=null;chosen=null;let clear=[];for(let i=0;i<10;i++){if(board[i].every(Boolean))clear.push(['r',i]);if(board.every(r=>r[i]))clear.push(['c',i])}clear.forEach(([t,i])=>{for(let q=0;q<10;q++)t==='r'?board[i][q]=null:board[q][i]=null});blockScore+=p.shape.length+clear.length*10;$('#block-score').textContent=blockScore;if(pieces.every(p=>!p))pieces=Array.from({length:3},()=>({shape:shapes[Math.floor(Math.random()*shapes.length)],color:colors[Math.floor(Math.random()*colors.length)]}));renderBlocks();if(!canPlace())setTimeout(()=>alert('No moves left! Final score: '+blockScore),50)}
function canPlace(){return pieces.filter(Boolean).some(p=>{for(let y=0;y<10;y++)for(let x=0;x<10;x++)if(!p.shape.some(([a,b])=>x+a>9||y+b>9||board[y+b][x+a]))return true;return false})}$('#blocks-restart').onclick=newBlocks;newBlocks();

// Tower defense
const tc=$('#tower-canvas'),tx=tc.getContext('2d');const path=[{x:-20,y:250},{x:180,y:250},{x:260,y:130},{x:470,y:130},{x:550,y:340},{x:780,y:340}];let towers=[], enemies=[], shots=[], selected='archer',gold=150,lives=12,wave=1,tdRun=false,spawnTimer,tdLoop;
function drawTower(){tx.fillStyle='#80bc72';tx.fillRect(0,0,760,500);for(let i=0;i<80;i++){tx.fillStyle='#6aaa62';tx.fillRect((i*83)%760,(i*147)%500,2,2)}tx.strokeStyle='#d7b56e';tx.lineWidth=36;tx.lineCap='round';tx.lineJoin='round';tx.beginPath();path.forEach((p,i)=>i?tx.lineTo(p.x,p.y):tx.moveTo(p.x,p.y));tx.stroke();tx.strokeStyle='#edcf87';tx.lineWidth=25;tx.stroke();tx.fillStyle='#5a6078';tx.fillRect(710,292,35,95);tx.fillStyle='#aeb3c0';tx.fillRect(705,280,45,18);towers.forEach(t=>{tx.font='28px sans-serif';tx.textAlign='center';tx.fillText(t.type==='archer'?'🏹':t.type==='guard'?'⚔️':'🔥',t.x,t.y+10);tx.strokeStyle='#ffffff55';tx.lineWidth=2;tx.beginPath();tx.arc(t.x,t.y,t.range,0,7);tx.stroke()});enemies.forEach(e=>{tx.fillStyle=e.type==='orc'?'#8a5c48':'#638a58';tx.beginPath();tx.arc(e.x,e.y,12,0,7);tx.fill();tx.fillStyle='#ed5d55';tx.fillRect(e.x-12,e.y-20,24,4);tx.fillStyle='#fff';tx.fillRect(e.x-12,e.y-20,24*(e.hp/e.max),4)});shots.forEach(s=>{tx.fillStyle='#f8ed83';tx.beginPath();tx.arc(s.x,s.y,4,0,7);tx.fill()})}
function tdTick(){enemies.forEach(e=>{e.pos+=e.speed;let d=0;while(d<path.length-1&&e.pos>Math.hypot(path[d+1].x-path[d].x,path[d+1].y-path[d].y)){e.pos-=Math.hypot(path[d+1].x-path[d].x,path[d+1].y-path[d].y);d++}if(d>=path.length-1){e.done=true;lives--;$('#lives').textContent=lives}else{let a=path[d],b=path[d+1],l=Math.hypot(b.x-a.x,b.y-a.y);e.x=a.x+(b.x-a.x)*e.pos/l;e.y=a.y+(b.y-a.y)*e.pos/l}});towers.forEach(t=>{t.cool--;let e=enemies.find(e=>!e.done&&Math.hypot(e.x-t.x,e.y-t.y)<t.range);if(e&&t.cool<=0){e.hp-=t.damage;t.cool=t.speed;shots.push({x:t.x,y:t.y,life:6});if(e.hp<=0){e.done=true;gold+=10;$('#gold').textContent=gold}}});enemies=enemies.filter(e=>!e.done);shots=shots.filter(s=>--s.life>0);drawTower();if(lives<=0)tdEnd('The keep has fallen!');else if(tdRun&&!enemies.length&&!spawnTimer){tdRun=false;$('#td-overlay').innerHTML='<h2>Wave complete!</h2><p>The kingdom is safe... for now.</p><button class="primary" id="td-start">Next wave <span>→</span></button>';$('#td-overlay').style.display='flex';$('#td-start').onclick=startWave}}
function startWave(){tdRun=true;$('#td-overlay').style.display='none';let count=7+wave*2;spawnTimer=setInterval(()=>{enemies.push({pos:0,speed:1.15+wave*.13,hp:24+wave*9,max:24+wave*9,type:Math.random()>.7?'orc':'goblin'});if(!--count){clearInterval(spawnTimer);spawnTimer=null;wave++;$('#wave-num').textContent=wave}},650);clearInterval(tdLoop);tdLoop=setInterval(tdTick,30)}
function tdEnd(t){clearInterval(tdLoop);clearInterval(spawnTimer);tdRun=false;$('#td-overlay').innerHTML='<h2>'+t+'</h2><p>You reached wave '+wave+'.</p><button class="primary" id="td-start">Restart <span>↻</span></button>';$('#td-overlay').style.display='flex';$('#td-start').onclick=resetTD}
function resetTD(){towers=[];enemies=[];gold=150;lives=12;wave=1;$('#gold').textContent=gold;$('#lives').textContent=lives;$('#wave-num').textContent=wave;drawTower();startWave()}
$$('.tower-choice').forEach(b=>b.onclick=()=>{$$('.tower-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.tower});tc.onclick=e=>{if(!$('#tower').classList.contains('active'))return;let r=tc.getBoundingClientRect(),x=(e.clientX-r.left)*760/r.width,y=(e.clientY-r.top)*500/r.height,cost=selected==='archer'?50:selected==='guard'?65:85;if(gold<cost)return;let nearPath=path.slice(0,-1).some((p,i)=>{let q=path[i+1],t=Math.max(0,Math.min(1,((x-p.x)*(q.x-p.x)+(y-p.y)*(q.y-p.y))/((q.x-p.x)**2+(q.y-p.y)**2)));return Math.hypot(x-(p.x+t*(q.x-p.x)),y-(p.y+t*(q.y-p.y)))<42});if(nearPath)return;towers.push({x,y,type:selected,range:selected==='wizard'?130:selected==='archer'?120:80,damage:selected==='wizard'?18:selected==='archer'?9:6,speed:selected==='wizard'?35:selected==='archer'?18:8,cool:0});gold-=cost;$('#gold').textContent=gold;drawTower()};$('#td-start').onclick=startWave;drawTower();
// Enhanced tower controls: cursor placement, top-down characters, barriers, and upgrades.
const tdBarriers=[{x:95,y:65,w:58,h:34},{x:330,y:215,w:72,h:38},{x:610,y:70,w:66,h:42},{x:610,y:420,w:82,h:34}];let tdGhost=null,tdSelectedTower=null,tdUpgradeButton;
function tdPoint(e){const r=tc.getBoundingClientRect();return{x:(e.clientX-r.left)*760/r.width,y:(e.clientY-r.top)*500/r.height}}
function tdBlocked(x,y,r=20){return tdBarriers.some(b=>x+r>b.x&&x-r<b.x+b.w&&y+r>b.y&&y-r<b.y+b.h)}
function drawPerson(t,ghost=false){tx.save();tx.globalAlpha=ghost?.48:1;tx.translate(t.x,t.y);tx.fillStyle='#232b4c';tx.beginPath();tx.arc(0,0,18,0,7);tx.fill();tx.fillStyle=t.type==='archer'?'#67c7a4':t.type==='guard'?'#f09a62':'#9078db';tx.beginPath();tx.arc(0,-3,11,0,7);tx.fill();tx.fillStyle='#f4c9a5';tx.beginPath();tx.arc(0,-13,7,0,7);tx.fill();tx.fillStyle='#302d4e';tx.beginPath();tx.arc(0,-16,7,Math.PI,Math.PI*2);tx.fill();tx.strokeStyle='#fff';tx.lineWidth=2;tx.beginPath();tx.moveTo(-9,11);tx.lineTo(-14,19);tx.moveTo(9,11);tx.lineTo(14,19);tx.stroke();if(t.type==='archer'){tx.strokeStyle='#f8ed83';tx.beginPath();tx.arc(13,0,10,-1.2,1.2);tx.stroke()}if(t.type==='guard'){tx.fillStyle='#d7e0ef';tx.fillRect(10,-4,7,13)}if(t.type==='wizard'){tx.fillStyle='#f8ed83';tx.beginPath();tx.arc(14,-8,4,0,7);tx.fill()}tx.restore()}
function drawBarrier(b){tx.fillStyle='#485267';tx.fillRect(b.x,b.y,b.w,b.h);tx.fillStyle='#68738a';for(let x=b.x+8;x<b.x+b.w-4;x+=18)tx.fillRect(x,b.y+6,11,7);tx.fillStyle='#30394f';tx.fillRect(b.x,b.y+b.h-7,b.w,7);}
const tdOldDraw=drawTower;drawTower=function(){tx.fillStyle='#80bc72';tx.fillRect(0,0,760,500);for(let i=0;i<80;i++){tx.fillStyle='#6aaa62';tx.fillRect((i*83)%760,(i*147)%500,2,2)}tx.strokeStyle='#d7b56e';tx.lineWidth=36;tx.lineCap='round';tx.lineJoin='round';tx.beginPath();path.forEach((p,i)=>i?tx.lineTo(p.x,p.y):tx.moveTo(p.x,p.y));tx.stroke();tx.strokeStyle='#edcf87';tx.lineWidth=25;tx.stroke();tdBarriers.forEach(drawBarrier);tx.fillStyle='#5a6078';tx.fillRect(710,292,35,95);tx.fillStyle='#aeb3c0';tx.fillRect(705,280,45,18);towers.forEach(t=>{tx.strokeStyle='#ffffff55';tx.lineWidth=2;tx.beginPath();tx.arc(t.x,t.y,t.range,0,7);tx.stroke();drawPerson(t)});if(tdGhost){let valid=tdGhost.x>20&&tdGhost.x<740&&tdGhost.y>20&&tdGhost.y<480&&!tdBlocked(tdGhost.x,tdGhost.y,22)&&!path.slice(0,-1).some((p,i)=>{let q=path[i+1],u=Math.max(0,Math.min(1,((tdGhost.x-p.x)*(q.x-p.x)+(tdGhost.y-p.y)*(q.y-p.y))/((q.x-p.x)**2+(q.y-p.y)**2)));return Math.hypot(tdGhost.x-(p.x+u*(q.x-p.x)),tdGhost.y-(p.y+u*(q.y-p.y)))<42});tx.fillStyle=valid?'#77d8a6':'#f45d52';tx.beginPath();tx.arc(tdGhost.x,tdGhost.y,24,0,7);tx.fill();drawPerson({...tdGhost,type:selected},true)}enemies.forEach(e=>{tx.fillStyle=e.type==='orc'?'#8a5c48':'#638a58';tx.beginPath();tx.arc(e.x,e.y,12,0,7);tx.fill();tx.fillStyle='#ed5d55';tx.fillRect(e.x-12,e.y-20,24,4);tx.fillStyle='#fff';tx.fillRect(e.x-12,e.y-20,24*(e.hp/e.max),4)});shots.forEach(s=>{tx.fillStyle='#f8ed83';tx.beginPath();tx.arc(s.x,s.y,4,0,7);tx.fill()})};
tdUpgradeButton=document.createElement('button');tdUpgradeButton.className='secondary td-upgrade';tdUpgradeButton.textContent='Select a tower to upgrade';$('.tower-select').append(tdUpgradeButton);function refreshUpgrade(){if(!tdSelectedTower){tdUpgradeButton.disabled=true;tdUpgradeButton.textContent='Select a tower to upgrade';return}let cost=tdSelectedTower.level*45;tdUpgradeButton.disabled=gold<cost;tdUpgradeButton.textContent='Upgrade level '+tdSelectedTower.level+' · '+cost+' gold'}tdUpgradeButton.onclick=()=>{if(!tdSelectedTower)return;let cost=tdSelectedTower.level*45;if(gold<cost)return;gold-=cost;tdSelectedTower.level++;tdSelectedTower.damage=Math.round(tdSelectedTower.damage*1.35);tdSelectedTower.range+=12;tdSelectedTower.speed=Math.max(4,tdSelectedTower.speed-2);$('#gold').textContent=gold;refreshUpgrade();drawTower()};
$$('.tower-choice').forEach(b=>b.onclick=()=>{$$('.tower-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.tower;tdSelectedTower=null;tdGhost={x:tc.width/2,y:tc.height/2,type:selected};refreshUpgrade();drawTower()});tc.onmousemove=e=>{if(tdGhost){tdGhost=tdPoint(e);tdGhost.type=selected;drawTower()}};tc.onmouseleave=()=>{tdGhost=null;drawTower()};tc.onclick=e=>{if(!$('#tower').classList.contains('active')||$('#td-overlay').style.display!=='none')return;let p=tdPoint(e),existing=towers.find(t=>Math.hypot(t.x-p.x,t.y-p.y)<24);if(existing){tdSelectedTower=existing;tdGhost=null;refreshUpgrade();drawTower();return}let cost=selected==='archer'?50:selected==='guard'?65:85;if(gold<cost||tdBlocked(p.x,p.y,22))return;let nearPath=path.slice(0,-1).some((a,i)=>{let b=path[i+1],u=Math.max(0,Math.min(1,((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/((b.x-a.x)**2+(b.y-a.y)**2)));return Math.hypot(p.x-(a.x+u*(b.x-a.x)),p.y-(a.y+u*(b.y-a.y)))<42});if(nearPath)return;towers.push({x:p.x,y:p.y,type:selected,level:1,range:selected==='wizard'?130:selected==='archer'?120:80,damage:selected==='wizard'?18:selected==='archer'?9:6,speed:selected==='wizard'?35:selected==='archer'?18:8,cool:0});gold-=cost;$('#gold').textContent=gold;tdGhost=null;drawTower()};const tdOriginalStart=$('#td-start').onclick;$('#td-start').onclick=()=>{tdGhost=null;tdOriginalStart()};refreshUpgrade();drawTower();
